In [3]:
my_list = [1, 2, 3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
 np.random.rand(5)

array([0.53863108, 0.26535315, 0.27337466, 0.66306187, 0.6808015 ])

In [28]:
np.random.randn(4,4)

array([[ 0.34180575,  1.11965846,  0.37793774,  2.07999705],
       [ 0.3384329 ,  1.88736883,  0.60783989, -0.51743362],
       [ 0.75595583, -1.85849859,  1.72851765, -2.65242224],
       [-0.65206521,  1.38176137, -0.93963636, -0.66982125]])

In [31]:
np.random.randint(1,100, 10)

array([47, 55, 95, 25, 65, 30,  4, 84, 48, 11])

In [39]:
arr = np.arange(30)

In [41]:
arr.reshape(3, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
ranarr = np.random.randint(0,50,10)

In [43]:
ranarr

array([26, 40, 21, 48, 34, 11, 19, 48, 11, 41])

In [44]:
ranarr.max()

48

In [45]:
ranarr.min()

11

In [46]:
ranarr.argmax()

3

In [47]:
ranarr.argmin()

5

In [53]:
ranarr = ranarr.reshape(2,5)

In [54]:
ranarr.shape

(2, 5)

In [55]:
ranarr.dtype

dtype('int64')